# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35c6b9fa7a3d358d1aae9f15ce41f6fef51943d0bf2ecdddecec52b252eb3c46c5a56722fbc5590daccf79116b531a46eb6b133fb1e3cafd2cacb22758a4625

test:
  secret_key_base: 080b6af3222e5d624b8c0439f821bd43489d58413ee7d776b7fd73f46196e123809c2bf38ce47768e43d295481df14a65fea7f05e77e7435eb4902ebe1b646d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
